import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (err) => console.log("PAGEERROR:", err.message.slice(0, 500)));
page.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE:", m.text().slice(0, 300)); });
await page.goto("http://localhost:3002/settings/theme");
await page.waitForTimeout(2500);
console.log("url:", page.url());
console.log("heading:", await page.getByRole("heading", { name: "Theme" }).count());
await page.getByTestId("theme-card-rose").click();
await page.waitForTimeout(1500);
console.log("after rose:", await page.getByTestId("theme-card-slate").count());
await page.getByTestId("theme-card-slate").click();
await page.waitForTimeout(1500);
console.log("after slate:", await page.getByTestId("theme-card-ocean").count());
await page.getByTestId("theme-card-ocean").click();
await page.waitForTimeout(1500);
console.log("after ocean:", await page.getByTestId("theme-card-amber").count());
await page.getByTestId("theme-card-amber").click();
await page.waitForTimeout(1000);
console.log("done, boundary visible:", await page.getByText("Something went wrong").count());
await browser.close();
