import type { ComponentManifest } from "../manifest-types";

export const transportManifest: ComponentManifest = {
  type: "transport",
  kind: "interactive",
  label: "Transport",
  summary: "Page clock: tempo, meter, count-in, play/pause, loop, and tempo ramp controls.",
  justification:
    "The Transport is the foundation of time-based page behavior. Every page with timed practice needs a single Transport to provide the master clock. The presence of a Transport determines whether a page is clock-advanced.",
  category: "rhythm",
  accepts: [],
  outputs: [],
  requires: [],
  configSpec: [
    {
      kind: "range",
      key: "bpm",
      label: "Tempo",
      min: 30,
      max: 300,
      step: 1,
      helperText: "Beats per minute",
    },
    {
      kind: "select",
      key: "beatsPerBar",
      label: "Beats per bar",
      options: [
        { label: "2", value: 2 },
        { label: "3", value: 3 },
        { label: "4", value: 4 },
        { label: "5", value: 5 },
        { label: "6", value: 6 },
        { label: "7", value: 7 },
        { label: "8", value: 8 },
        { label: "9", value: 9 },
        { label: "12", value: 12 },
      ],
    },
    {
      kind: "range",
      key: "countInBars",
      label: "Count-in bars",
      min: 0,
      max: 8,
      step: 1,
      helperText: "Bars of silence before practice starts",
    },
    {
      kind: "toggle",
      key: "loopEnabled",
      label: "Loop section",
      helperText: "Repeat the selected bar range",
    },
    {
      kind: "range",
      key: "loopStartBar",
      label: "Loop start",
      min: 0,
      max: 128,
      step: 1,
    },
    {
      kind: "range",
      key: "loopEndBar",
      label: "Loop end",
      min: 0,
      max: 128,
      step: 1,
    },
    {
      kind: "toggle",
      key: "rampEnabled",
      label: "Tempo ramp",
      helperText: "Gradually increase tempo during practice",
    },
    {
      kind: "range",
      key: "rampTargetBpm",
      label: "Target tempo",
      min: 30,
      max: 300,
      step: 1,
      helperText: "BPM to reach by the end of the ramp",
    },
  ],
  defaultSize: { w: 4, h: 2 },
  minSize: { w: 2, h: 1 },
  maxPerPage: 1,
  docsPath: "docs/components/transport.md",
  status: "stable",
};
